export const venues = [
  {
    id: '1',
    name: 'The Grand Ballroom Estate',
    type: 'Ballroom',
    location: 'Beverly Hills, CA',
    rating: 4.9,
    reviewCount: 128,
    capacity: 350,
    price: 15000,
    image: '',
  },
  {
    id: '2',
    name: 'Rustic Barn Retreat',
    type: 'Barn',
    location: 'Napa Valley, CA',
    rating: 4.8,
    reviewCount: 95,
    capacity: 200,
    price: 8500,
    image: '',
  },
  {
    id: '3',
    name: 'Oceanview Beach Club',
    type: 'Beach',
    location: 'Malibu, CA',
    rating: 4.9,
    reviewCount: 156,
    capacity: 250,
    price: 20000,
    image: '',
  },
];

export const catering = [
  {
    id: '1',
    name: 'Elegance Fine Dining',
    rating: 4.9,
    reviewCount: 203,
    specialties: ['Truffle Risotto', 'Pan-seared Sea Bass'],
    minGuests: 50,
    pricePerHead: 150,
    image: '',
  },
  {
    id: '2',
    name: 'Harvest Table Catering',
    rating: 4.8,
    reviewCount: 167,
    specialties: ['Seasonal Salads', 'Herb-roasted Chicken'],
    minGuests: 30,
    pricePerHead: 95,
    image: '',
  },
  {
    id: '3',
    name: 'Sugar Bloom Desserts',
    rating: 4.9,
    reviewCount: 241,
    specialties: ['Custom Wedding Cakes', 'Macaron Towers'],
    minGuests: 20,
    pricePerHead: 45,
    image: '',
  },
];
