export const venueTypes = [
  'All',
  'Ballroom',
  'Barn',
  'Beach',
  'Garden',
  'Hotel',
  'Restaurant',
];

export const venues = [
  {
    id: '1',
    name: 'The Grand Ballroom Estate',
    type: 'Ballroom',
    location: 'Beverly Hills, CA',
    rating: 4.9,
    reviewCount: 128,
    capacity: 350,
    price: 15000,
    image: '',
    description: 'An elegant ballroom featuring crystal chandeliers, marble floors, and floor-to-ceiling windows with stunning city views. Perfect for luxurious wedding celebrations.',
  },
  {
    id: '2',
    name: 'Rustic Barn Retreat',
    type: 'Barn',
    location: 'Napa Valley, CA',
    rating: 4.8,
    reviewCount: 95,
    capacity: 200,
    price: 8500,
    image: '',
    description: 'A charming rustic barn surrounded by vineyards, offering an authentic countryside experience with modern amenities and breathtaking sunset views.',
  },
  {
    id: '3',
    name: 'Oceanview Beach Club',
    type: 'Beach',
    location: 'Malibu, CA',
    rating: 4.9,
    reviewCount: 156,
    capacity: 250,
    price: 20000,
    image: '',
    description: 'Experience the magic of a beachfront celebration with pristine white sands, crystal-clear waters, and spectacular Pacific Ocean sunsets.',
  },
];

export const catering = [
  {
    id: '1',
    name: 'Elegance Fine Dining',
    rating: 4.9,
    reviewCount: 203,
    specialties: ['Truffle Risotto', 'Pan-seared Sea Bass'],
    minGuests: 50,
    pricePerHead: 150,
    image: '',
  },
  {
    id: '2',
    name: 'Harvest Table Catering',
    rating: 4.8,
    reviewCount: 167,
    specialties: ['Seasonal Salads', 'Herb-roasted Chicken'],
    minGuests: 30,
    pricePerHead: 95,
    image: '',
  },
  {
    id: '3',
    name: 'Sugar Bloom Desserts',
    rating: 4.9,
    reviewCount: 241,
    specialties: ['Custom Wedding Cakes', 'Macaron Towers'],
    minGuests: 20,
    pricePerHead: 45,
    image: '',
  },
];
